### ISSUE TITLE
Lockdown started early

### ISSUE THREAD

**Issue by smiley1983** [riddlesio/light-riders-engine#12]
Lockdown seems to have begun, current time in UTC is 11:09 pm Sunday, 22 October 2017.

I'd really like to activate my 79th submission, but currently the 81st is active. I ran tests overnight  and got up with plenty of time to make one last adjustment to the active version, but lockdown had begun a few minutes before I awoke, well before the nominal lockdown time of midnight UTC.

**Comment by JimVanEeden** [comment]
You are right, I made the mistake to set the lockdown time to our local timezone. Bot submissions will be allowed today only.
